/*----- PROTECTED REGION ID(EvTesterDSClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        EvTesterDSClass.h
//
// description : Include for the EvTesterDS root class.
//               This class is the singleton class for
//                the EvTesterDS device class.
//               It contains all properties and methods which the 
//               EvTesterDS requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef EvTesterDSClass_H
#define EvTesterDSClass_H

#include <tango.h>
#include <EvTesterDS.h>


/*----- PROTECTED REGION END -----*/	//	EvTesterDSClass.h


namespace EvTesterDS_ns
{
/*----- PROTECTED REGION ID(EvTesterDSClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	EvTesterDSClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute adouble class definition
class adoubleAttrib: public Tango::Attr
{
public:
	adoubleAttrib():Attr("adouble",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~adoubleAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<EvTesterDS *>(dev))->read_adouble(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<EvTesterDS *>(dev))->is_adouble_allowed(ty);}
};

//	Attribute adataready class definition
class adatareadyAttrib: public Tango::Attr
{
public:
	adatareadyAttrib():Attr("adataready",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~adatareadyAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<EvTesterDS *>(dev))->read_adataready(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<EvTesterDS *>(dev))->is_adataready_allowed(ty);}
};


/**
 *	The EvTesterDSClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  EvTesterDSClass : public Tango::DeviceClass
#else
class EvTesterDSClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(EvTesterDSClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	EvTesterDSClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static EvTesterDSClass *init(const char *);
		static EvTesterDSClass *instance();
		~EvTesterDSClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		EvTesterDSClass(string &);
		static EvTesterDSClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	EvTesterDS_H
