/*----- PROTECTED REGION ID(EvTesterDSStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        EvTesterDSStateMachine.cpp
//
// description : State machine file for the EvTesterDS class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <EvTesterDS.h>

/*----- PROTECTED REGION END -----*/	//	EvTesterDS::EvTesterDSStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace EvTesterDS_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : EvTesterDS::is_adouble_allowed()
 *	Description : Execution allowed for adouble attribute
 */
//--------------------------------------------------------
bool EvTesterDS::is_adouble_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for adouble attribute in read access.
	/*----- PROTECTED REGION ID(EvTesterDS::adoubleStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EvTesterDS::adoubleStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : EvTesterDS::is_adataready_allowed()
 *	Description : Execution allowed for adataready attribute
 */
//--------------------------------------------------------
bool EvTesterDS::is_adataready_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for adataready attribute in read access.
	/*----- PROTECTED REGION ID(EvTesterDS::adatareadyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EvTesterDS::adatareadyStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

}	//	End of namespace
