/*----- PROTECTED REGION ID(Gps.h) ENABLED START -----*/
//=============================================================================
//
// file :        Gps.h
//
// description : Include file for the Gps class
//
// project :     gps ds usb/serial
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Gps_H
#define Gps_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	Gps.h

/**
 *  Gps class description:
 *    use Serial
 *    nmea
 */

namespace Gps_ns
{
/*----- PROTECTED REGION ID(Gps::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	Gps::Additional Class Declarations

class Gps : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(Gps::Data Members) ENABLED START -----*/

//	Add your own data members
	Tango::DeviceProxy *serial_line;

/*----- PROTECTED REGION END -----*/	//	Gps::Data Members


//	Attribute data members
public:
	Tango::DevString	*attr_nmea_read;
	string s;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Gps(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Gps(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	Gps(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~Gps() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : Gps::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute nmea related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_nmea(Tango::Attribute &attr);
	virtual bool is_nmea_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : Gps::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:


	//--------------------------------------------------------
	/**
	 *	Method      : Gps::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(Gps::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	Gps::Additional Method prototypes
};

/*----- PROTECTED REGION ID(Gps::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	Gps::Additional Classes Definitions

}	//	End of namespace

#endif   //	Gps_H
