/*----- PROTECTED REGION ID(GpsStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        GpsStateMachine.cpp
//
// description : State machine file for the Gps class
//
// project :     gps ds usb/serial
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Gps.h>

/*----- PROTECTED REGION END -----*/	//	Gps::GpsStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Gps_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Gps::is_nmea_allowed()
 *	Description : Execution allowed for nmea attribute
 */
//--------------------------------------------------------
bool Gps::is_nmea_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for nmea attribute in read access.
	/*----- PROTECTED REGION ID(Gps::nmeaStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Gps::nmeaStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

}	//	End of namespace
