/*----- PROTECTED REGION ID(MyFirstDS.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        MyFirstDS.cpp
//
// description : C++ source for the MyFirstDS class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               MyFirstDS are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <MyFirstDS.h>
#include <MyFirstDSClass.h>

/*----- PROTECTED REGION END -----*/	//	MyFirstDS.cpp

/**
 *  MyFirstDS class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  MyCmd         |  my_cmd
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//  MyAttr  |  Tango::DevDouble	Scalar
//================================================================

namespace MyFirstDS_ns
{
/*----- PROTECTED REGION ID(MyFirstDS::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	MyFirstDS::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : MyFirstDS::MyFirstDS()
 *	Description : Constructors for a Tango device
 *                implementing the classMyFirstDS
 */
//--------------------------------------------------------
MyFirstDS::MyFirstDS(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(MyFirstDS::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::constructor_1
}
//--------------------------------------------------------
MyFirstDS::MyFirstDS(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(MyFirstDS::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::constructor_2
}
//--------------------------------------------------------
MyFirstDS::MyFirstDS(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(MyFirstDS::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : MyFirstDS::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void MyFirstDS::delete_device()
{
	DEBUG_STREAM << "MyFirstDS::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(MyFirstDS::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::delete_device
	delete[] attr_MyAttr_read;
}

//--------------------------------------------------------
/**
 *	Method      : MyFirstDS::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void MyFirstDS::init_device()
{
	DEBUG_STREAM << "MyFirstDS::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(MyFirstDS::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::init_device_before
	
	//	No device property to be read from database
	
	attr_MyAttr_read = new Tango::DevDouble[1];
	/*----- PROTECTED REGION ID(MyFirstDS::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::init_device
}


//--------------------------------------------------------
/**
 *	Method      : MyFirstDS::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void MyFirstDS::always_executed_hook()
{
	DEBUG_STREAM << "MyFirstDS::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(MyFirstDS::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : MyFirstDS::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void MyFirstDS::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "MyFirstDS::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(MyFirstDS::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute MyAttr related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MyFirstDS::read_MyAttr(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MyFirstDS::read_MyAttr(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(MyFirstDS::read_MyAttr) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_MyAttr_read);
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::read_MyAttr
}

//--------------------------------------------------------
/**
 *	Method      : MyFirstDS::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void MyFirstDS::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(MyFirstDS::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command MyCmd related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void MyFirstDS::my_cmd()
{
	DEBUG_STREAM << "MyFirstDS::MyCmd()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(MyFirstDS::my_cmd) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::my_cmd
}

/*----- PROTECTED REGION ID(MyFirstDS::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	MyFirstDS::namespace_ending
} //	namespace
