/*----- PROTECTED REGION ID(MyFirstDSStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        MyFirstDSStateMachine.cpp
//
// description : State machine file for the MyFirstDS class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <MyFirstDS.h>

/*----- PROTECTED REGION END -----*/	//	MyFirstDS::MyFirstDSStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace MyFirstDS_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MyFirstDS::is_MyAttr_allowed()
 *	Description : Execution allowed for MyAttr attribute
 */
//--------------------------------------------------------
bool MyFirstDS::is_MyAttr_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for MyAttr attribute in read access.
	/*----- PROTECTED REGION ID(MyFirstDS::MyAttrStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::MyAttrStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MyFirstDS::is_MyCmd_allowed()
 *	Description : Execution allowed for MyCmd attribute
 */
//--------------------------------------------------------
bool MyFirstDS::is_MyCmd_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for MyCmd command.
	/*----- PROTECTED REGION ID(MyFirstDS::MyCmdStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MyFirstDS::MyCmdStateAllowed
	return true;
}

}	//	End of namespace
