#!/usr/bin/env python
# -*- coding:utf-8 -*- 


##############################################################################
## license :
##============================================================================
##
## File :        ChainableRGBLed.py
## 
## Project :     
##
## This file is part of Tango device class.
## 
## Tango is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Tango is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Tango.  If not, see <http://www.gnu.org/licenses/>.
## 
##
## $Author :      rponsard$
##
## $Revision :    $
##
## $Date :        $
##
## $HeadUrl :     $
##============================================================================
##            This file is generated by POGO
##    (Program Obviously used to Generate tango Object)
##
##        (c) - Software Engineering Group - ESRF
##############################################################################

"""device server for grove chainable rgb led from seeedstudio"""

__all__ = ["ChainableRGBLed", "ChainableRGBLedClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(ChainableRGBLed.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	ChainableRGBLed.additionnal_import

## Device States Description
## No states for this device

class ChainableRGBLed (PyTango.Device_4Impl):

    #--------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(ChainableRGBLed.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	ChainableRGBLed.global_variables

    def __init__(self,cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        ChainableRGBLed.init_device(self)
        #----- PROTECTED REGION ID(ChainableRGBLed.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ChainableRGBLed.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(ChainableRGBLed.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ChainableRGBLed.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        #----- PROTECTED REGION ID(ChainableRGBLed.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ChainableRGBLed.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(ChainableRGBLed.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ChainableRGBLed.always_executed_hook

    #-----------------------------------------------------------------------------
    #    ChainableRGBLed read/write attribute methods
    #-----------------------------------------------------------------------------
    
    
    
        #----- PROTECTED REGION ID(ChainableRGBLed.initialize_dynamic_attributes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ChainableRGBLed.initialize_dynamic_attributes
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(ChainableRGBLed.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ChainableRGBLed.read_attr_hardware


    #-----------------------------------------------------------------------------
    #    ChainableRGBLed command methods
    #-----------------------------------------------------------------------------
    
    def SetRGB(self, argin):
        """ 
        
        :param argin: R G B LedNum
        :type: PyTango.DevVarUShortArray
        :return: 
        :rtype: PyTango.DevVoid """
        self.debug_stream("In SetRGB()")
        #----- PROTECTED REGION ID(ChainableRGBLed.SetRGB) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ChainableRGBLed.SetRGB
        

    #----- PROTECTED REGION ID(ChainableRGBLed.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	ChainableRGBLed.programmer_methods

class ChainableRGBLedClass(PyTango.DeviceClass):
    #--------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(ChainableRGBLed.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	ChainableRGBLed.global_class_variables

    def dyn_attr(self, dev_list):
        """Invoked to create dynamic attributes for the given devices.
        Default implementation calls
        :meth:`ChainableRGBLed.initialize_dynamic_attributes` for each device
    
        :param dev_list: list of devices
        :type dev_list: :class:`PyTango.DeviceImpl`"""
    
        for dev in dev_list:
            try:
                dev.initialize_dynamic_attributes()
            except:
                import traceback
                dev.warn_stream("Failed to initialize dynamic attributes")
                dev.debug_stream("Details: " + traceback.format_exc())
        #----- PROTECTED REGION ID(ChainableRGBLed.dyn_attr) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ChainableRGBLed.dyn_attr

    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        'SetRGB':
            [[PyTango.DevVarUShortArray, "R G B LedNum"],
            [PyTango.DevVoid, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(ChainableRGBLedClass,ChainableRGBLed,'ChainableRGBLed')
        #----- PROTECTED REGION ID(ChainableRGBLed.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ChainableRGBLed.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed,e:
        print '-------> Received a DevFailed exception:',e
    except Exception,e:
        print '-------> An unforeseen exception occured....',e

if __name__ == '__main__':
    main()
