#!/usr/bin/python3
# -*- coding:utf-8 -*-

# ############################################################################
#  license :
# ============================================================================
#
#  File :        XilinxRng.py
#
#  Project :     Embedded Community Conference
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      rponsard$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["XilinxRng", "XilinxRngClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(XilinxRng.additionnal_import) ENABLED START -----#
import random

#----- PROTECTED REGION END -----#	//	XilinxRng.additionnal_import

# Device States Description
# ON : 
# OFF : 


class XilinxRng (PyTango.Device_4Impl):
    """pseudo rng"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(XilinxRng.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	XilinxRng.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        XilinxRng.init_device(self)
        #----- PROTECTED REGION ID(XilinxRng.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	XilinxRng.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(XilinxRng.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	XilinxRng.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Random_read = 0.0
        #----- PROTECTED REGION ID(XilinxRng.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	XilinxRng.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(XilinxRng.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	XilinxRng.always_executed_hook

    # -------------------------------------------------------------------------
    #    XilinxRng read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_Random(self, attr):
        self.debug_stream("In read_Random()")
        #----- PROTECTED REGION ID(XilinxRng.Random_read) ENABLED START -----#
        self.attr_Random_read=random.random()
        attr.set_value(self.attr_Random_read)
        
        #----- PROTECTED REGION END -----#	//	XilinxRng.Random_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(XilinxRng.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	XilinxRng.read_attr_hardware


    # -------------------------------------------------------------------------
    #    XilinxRng command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(XilinxRng.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	XilinxRng.programmer_methods

class XilinxRngClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(XilinxRng.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	XilinxRng.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'Random':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(XilinxRngClass, XilinxRng, 'XilinxRng')
        #----- PROTECTED REGION ID(XilinxRng.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	XilinxRng.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
