#!/usr/bin/env python
# -*- coding:utf-8 -*- 


##############################################################################
## license :
##============================================================================
##
## File :        GertBoardds.py
## 
## Project :     
##
## This file is part of Tango device class.
## 
## Tango is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Tango is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Tango.  If not, see <http://www.gnu.org/licenses/>.
## 
##
## $Author :      rp$
##
## $Revision :    $
##
## $Date :        $
##
## $HeadUrl :     $
##============================================================================
##            This file is generated by POGO
##    (Program Obviously used to Generate tango Object)
##
##        (c) - Software Engineering Group - ESRF
##############################################################################

"""raspberry pi gertboard I/O example"""

__all__ = ["GertBoardds", "GertBoarddsClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(GertBoardds.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	GertBoardds.additionnal_import

## Device States Description
## No states for this device

class GertBoardds (PyTango.Device_4Impl):

    #--------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(GertBoardds.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	GertBoardds.global_variables

    def __init__(self,cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        GertBoardds.init_device(self)
        #----- PROTECTED REGION ID(GertBoardds.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(GertBoardds.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_leds_read = [False]
        self.attr_switches_read = [False]
        #----- PROTECTED REGION ID(GertBoardds.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(GertBoardds.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.always_executed_hook

    #-----------------------------------------------------------------------------
    #    GertBoardds read/write attribute methods
    #-----------------------------------------------------------------------------
    
    def read_leds(self, attr):
        self.debug_stream("In read_leds()")
        #----- PROTECTED REGION ID(GertBoardds.leds_read) ENABLED START -----#
        attr.set_value(self.attr_leds_read)
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.leds_read
        
    def write_leds(self, attr):
        self.debug_stream("In write_leds()")
        data=attr.get_write_value()
        #----- PROTECTED REGION ID(GertBoardds.leds_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.leds_write
        
    def read_switches(self, attr):
        self.debug_stream("In read_switches()")
        #----- PROTECTED REGION ID(GertBoardds.switches_read) ENABLED START -----#
        attr.set_value(self.attr_switches_read)
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.switches_read
        
    
    
        #----- PROTECTED REGION ID(GertBoardds.initialize_dynamic_attributes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.initialize_dynamic_attributes
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(GertBoardds.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.read_attr_hardware


    #-----------------------------------------------------------------------------
    #    GertBoardds command methods
    #-----------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(GertBoardds.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	GertBoardds.programmer_methods

class GertBoarddsClass(PyTango.DeviceClass):
    #--------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(GertBoardds.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	GertBoardds.global_class_variables

    def dyn_attr(self, dev_list):
        """Invoked to create dynamic attributes for the given devices.
        Default implementation calls
        :meth:`GertBoardds.initialize_dynamic_attributes` for each device
    
        :param dev_list: list of devices
        :type dev_list: :class:`PyTango.DeviceImpl`"""
    
        for dev in dev_list:
            try:
                dev.initialize_dynamic_attributes()
            except:
                import traceback
                dev.warn_stream("Failed to initialize dynamic attributes")
                dev.debug_stream("Details: " + traceback.format_exc())
        #----- PROTECTED REGION ID(GertBoardds.dyn_attr) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.dyn_attr

    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'leds':
            [[PyTango.DevBoolean,
            PyTango.SPECTRUM,
            PyTango.READ_WITH_WRITE, 8]],
        'switches':
            [[PyTango.DevBoolean,
            PyTango.SPECTRUM,
            PyTango.READ, 3]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(GertBoarddsClass,GertBoardds,'GertBoardds')
        #----- PROTECTED REGION ID(GertBoardds.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	GertBoardds.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed,e:
        print '-------> Received a DevFailed exception:',e
    except Exception,e:
        print '-------> An unforeseen exception occured....',e

if __name__ == '__main__':
    main()
