/*----- PROTECTED REGION ID(UsbCam.h) ENABLED START -----*/
//=============================================================================
//
// file :        UsbCam.h
//
// description : Include file for the UsbCam class
//
// project :     a Tango DS for usb webcam
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef UsbCam_H
#define UsbCam_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	UsbCam.h

/**
 *  UsbCam class description:
 *    use v4l
 */

namespace UsbCam_ns
{
/*----- PROTECTED REGION ID(UsbCam::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations
struct buffer {
        void *                  start;
        size_t                  length;
};

/*----- PROTECTED REGION END -----*/	//	UsbCam::Additional Class Declarations

class UsbCam : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(UsbCam::Data Members) ENABLED START -----*/

//	Add your own data members

             

struct buffer *  buffers         = NULL;
unsigned int     n_buffers       = 0,width=176,height=144;
char deviceName[20];
int fd;

/*----- PROTECTED REGION END -----*/	//	UsbCam::Data Members


//	Attribute data members
public:
	Tango::DevDouble	*attr_random_read;
	Tango::DevDouble	*attr_myscalar_read;
	Tango::DevUChar	*attr_img_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	UsbCam(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	UsbCam(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	UsbCam(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~UsbCam() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : UsbCam::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute random related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_random(Tango::Attribute &attr);
	virtual bool is_random_allowed(Tango::AttReqType type);
/**
 *	Attribute myscalar related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_myscalar(Tango::Attribute &attr);
	virtual bool is_myscalar_allowed(Tango::AttReqType type);
/**
 *	Attribute img related methods
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Image max = 176 x 144
 */
	virtual void read_img(Tango::Attribute &attr);
	virtual bool is_img_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : UsbCam::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command TakePhoto related method
	 *	Description: 
	 *
	 */
	virtual void take_photo();
	virtual bool is_TakePhoto_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : UsbCam::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(UsbCam::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	UsbCam::Additional Method prototypes
};

/*----- PROTECTED REGION ID(UsbCam::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	UsbCam::Additional Classes Definitions

}	//	End of namespace

#endif   //	UsbCam_H
