/*----- PROTECTED REGION ID(UsbCamClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        UsbCamClass.h
//
// description : Include for the UsbCam root class.
//               This class is the singleton class for
//                the UsbCam device class.
//               It contains all properties and methods which the 
//               UsbCam requires only once e.g. the commands.
//
// project :     a Tango DS for usb webcam
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef UsbCamClass_H
#define UsbCamClass_H

#include <tango.h>
#include <UsbCam.h>


/*----- PROTECTED REGION END -----*/	//	UsbCamClass.h


namespace UsbCam_ns
{
/*----- PROTECTED REGION ID(UsbCamClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	UsbCamClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute random class definition
class randomAttrib: public Tango::Attr
{
public:
	randomAttrib():Attr("random",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~randomAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<UsbCam *>(dev))->read_random(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<UsbCam *>(dev))->is_random_allowed(ty);}
};

//	Attribute myscalar class definition
class myscalarAttrib: public Tango::Attr
{
public:
	myscalarAttrib():Attr("myscalar",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~myscalarAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<UsbCam *>(dev))->read_myscalar(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<UsbCam *>(dev))->is_myscalar_allowed(ty);}
};

//	Attribute img class definition
class imgAttrib: public Tango::ImageAttr
{
public:
	imgAttrib():ImageAttr("img",
			Tango::DEV_UCHAR, Tango::READ, 176, 144) {};
	~imgAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<UsbCam *>(dev))->read_img(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<UsbCam *>(dev))->is_img_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command TakePhoto class definition
class TakePhotoClass : public Tango::Command
{
public:
	TakePhotoClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	TakePhotoClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~TakePhotoClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<UsbCam *>(dev))->is_TakePhoto_allowed(any);}
};


/**
 *	The UsbCamClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  UsbCamClass : public Tango::DeviceClass
#else
class UsbCamClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(UsbCamClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	UsbCamClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static UsbCamClass *init(const char *);
		static UsbCamClass *instance();
		~UsbCamClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		UsbCamClass(string &);
		static UsbCamClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	UsbCam_H
