#!/usr/bin/env python
# -*- coding:utf-8 -*- 


##############################################################################
## license :
##============================================================================
##
## File :        UltrasonicSensor.py
## 
## Project :     
##
## This file is part of Tango device class.
## 
## Tango is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Tango is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Tango.  If not, see <http://www.gnu.org/licenses/>.
## 
##
## $Author :      rponsard$
##
## $Revision :    $
##
## $Date :        $
##
## $HeadUrl :     $
##============================================================================
##            This file is generated by POGO
##    (Program Obviously used to Generate tango Object)
##
##        (c) - Software Engineering Group - ESRF
##############################################################################

"""grove seeedstudio ultrasonic ranger """

__all__ = ["UltrasonicSensor", "UltrasonicSensorClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(UltrasonicSensor.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	UltrasonicSensor.additionnal_import

## Device States Description
## No states for this device

class UltrasonicSensor (PyTango.Device_4Impl):

    #--------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(UltrasonicSensor.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	UltrasonicSensor.global_variables

    def __init__(self,cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        UltrasonicSensor.init_device(self)
        #----- PROTECTED REGION ID(UltrasonicSensor.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	UltrasonicSensor.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(UltrasonicSensor.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	UltrasonicSensor.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Range_read = 0.0
        #----- PROTECTED REGION ID(UltrasonicSensor.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	UltrasonicSensor.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(UltrasonicSensor.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	UltrasonicSensor.always_executed_hook

    #-----------------------------------------------------------------------------
    #    UltrasonicSensor read/write attribute methods
    #-----------------------------------------------------------------------------
    
    def read_Range(self, attr):
        self.debug_stream("In read_Range()")
        #----- PROTECTED REGION ID(UltrasonicSensor.Range_read) ENABLED START -----#
        attr.set_value(self.attr_Range_read)
        
        #----- PROTECTED REGION END -----#	//	UltrasonicSensor.Range_read
        
    
    
        #----- PROTECTED REGION ID(UltrasonicSensor.initialize_dynamic_attributes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	UltrasonicSensor.initialize_dynamic_attributes
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(UltrasonicSensor.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	UltrasonicSensor.read_attr_hardware


    #-----------------------------------------------------------------------------
    #    UltrasonicSensor command methods
    #-----------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(UltrasonicSensor.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	UltrasonicSensor.programmer_methods

class UltrasonicSensorClass(PyTango.DeviceClass):
    #--------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(UltrasonicSensor.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	UltrasonicSensor.global_class_variables

    def dyn_attr(self, dev_list):
        """Invoked to create dynamic attributes for the given devices.
        Default implementation calls
        :meth:`UltrasonicSensor.initialize_dynamic_attributes` for each device
    
        :param dev_list: list of devices
        :type dev_list: :class:`PyTango.DeviceImpl`"""
    
        for dev in dev_list:
            try:
                dev.initialize_dynamic_attributes()
            except:
                import traceback
                dev.warn_stream("Failed to initialize dynamic attributes")
                dev.debug_stream("Details: " + traceback.format_exc())
        #----- PROTECTED REGION ID(UltrasonicSensor.dyn_attr) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	UltrasonicSensor.dyn_attr

    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'Range':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(UltrasonicSensorClass,UltrasonicSensor,'UltrasonicSensor')
        #----- PROTECTED REGION ID(UltrasonicSensor.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	UltrasonicSensor.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed,e:
        print '-------> Received a DevFailed exception:',e
    except Exception,e:
        print '-------> An unforeseen exception occured....',e

if __name__ == '__main__':
    main()
