#!/usr/bin/env python
# -*- coding:utf-8 -*- 


##############################################################################
## license :
##============================================================================
##
## File :        K2000.py
## 
## Project :     
##
## This file is part of Tango device class.
## 
## Tango is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Tango is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Tango.  If not, see <http://www.gnu.org/licenses/>.
## 
##
## $Author :      rp$
##
## $Revision :    $
##
## $Date :        $
##
## $HeadUrl :     $
##============================================================================
##            This file is generated by POGO
##    (Program Obviously used to Generate tango Object)
##
##        (c) - Software Engineering Group - ESRF
##############################################################################

"""use gertboard"""

__all__ = ["K2000", "K2000Class", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(K2000.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	K2000.additionnal_import

## Device States Description
## No states for this device

class K2000 (PyTango.Device_4Impl):

    #--------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(K2000.global_variables) ENABLED START -----#
    dev=PyTango.DeviceProxy("rp/raspberry/1")
    #----- PROTECTED REGION END -----#	//	K2000.global_variables

    def __init__(self,cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        K2000.init_device(self)
        #----- PROTECTED REGION ID(K2000.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	K2000.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(K2000.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	K2000.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        #----- PROTECTED REGION ID(K2000.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	K2000.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(K2000.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	K2000.always_executed_hook

    #-----------------------------------------------------------------------------
    #    K2000 read/write attribute methods
    #-----------------------------------------------------------------------------
    
    
    
        #----- PROTECTED REGION ID(K2000.initialize_dynamic_attributes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	K2000.initialize_dynamic_attributes
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(K2000.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	K2000.read_attr_hardware


    #-----------------------------------------------------------------------------
    #    K2000 command methods
    #-----------------------------------------------------------------------------
    
    def testGPIO(self, argin):
        """ 
        
        :param argin: led to blink
        :type: PyTango.DevLong
        :return: 
        :rtype: PyTango.DevVoid """
        self.debug_stream("In testGPIO()"+str((int)(argin/2)))
        #----- PROTECTED REGION ID(K2000.testGPIO) ENABLED START -----#
        K2000.dev.leds=[argin%2==1,((int)(argin/2))%2==1]
        #----- PROTECTED REGION END -----#	//	K2000.testGPIO
        

    #----- PROTECTED REGION ID(K2000.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	K2000.programmer_methods

class K2000Class(PyTango.DeviceClass):
    #--------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(K2000.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	K2000.global_class_variables

    def dyn_attr(self, dev_list):
        """Invoked to create dynamic attributes for the given devices.
        Default implementation calls
        :meth:`K2000.initialize_dynamic_attributes` for each device
    
        :param dev_list: list of devices
        :type dev_list: :class:`PyTango.DeviceImpl`"""
    
        for dev in dev_list:
            try:
                dev.initialize_dynamic_attributes()
            except:
                import traceback
                dev.warn_stream("Failed to initialize dynamic attributes")
                dev.debug_stream("Details: " + traceback.format_exc())
        #----- PROTECTED REGION ID(K2000.dyn_attr) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	K2000.dyn_attr

    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        'testGPIO':
            [[PyTango.DevLong, "led to blink"],
            [PyTango.DevVoid, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(K2000Class,K2000,'K2000')
        #----- PROTECTED REGION ID(K2000.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	K2000.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ("-------> Received a DevFailed exception:",e)
    except Exception as e:
        print ("-------> An unforeseen exception occured....",e)

if __name__ == '__main__':
    main()
