/*----- PROTECTED REGION ID(Scopix.h) ENABLED START -----*/
//=============================================================================
//
// file :        Scopix.h
//
// description : Include file for the Scopix class
//
// project :     scopix handeld oscilloscope
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Scopix_H
#define Scopix_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	Scopix.h

/**
 *  Scopix class description:
 *    OW 7062-C
 *    use serialline class
 */

namespace Scopix_ns
{
/*----- PROTECTED REGION ID(Scopix::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	Scopix::Additional Class Declarations

class Scopix : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(Scopix::Data Members) ENABLED START -----*/

//	Add your own data members
Tango::DeviceProxy *serial_line;


/*----- PROTECTED REGION END -----*/	//	Scopix::Data Members


//	Attribute data members
public:
	Tango::DevDouble	*attr_Input1_read;
	Tango::DevDouble	*attr_Spectrum1_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Scopix(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Scopix(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	Scopix(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~Scopix() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : Scopix::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute Input1 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Input1(Tango::Attribute &attr);
	virtual bool is_Input1_allowed(Tango::AttReqType type);
/**
 *	Attribute Spectrum1 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 2500
 */
	virtual void read_Spectrum1(Tango::Attribute &attr);
	virtual bool is_Spectrum1_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : Scopix::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command Idn related method
	 *	Description: 
	 *
	 *	@returns scopix id
	 */
	virtual Tango::DevString idn();
	virtual bool is_Idn_allowed(const CORBA::Any &any);
	/**
	 *	Command Date related method
	 *	Description: 
	 *
	 *	@returns 
	 */
	virtual Tango::DevString date();
	virtual bool is_Date_allowed(const CORBA::Any &any);
	/**
	 *	Command Time related method
	 *	Description: 
	 *
	 *	@returns 
	 */
	virtual Tango::DevString time();
	virtual bool is_Time_allowed(const CORBA::Any &any);
	/**
	 *	Command GpibCmd related method
	 *	Description: 
	 *
	 *	@param argin 
	 *	@returns 
	 */
	virtual Tango::DevString gpib_cmd(Tango::DevString argin);
	virtual bool is_GpibCmd_allowed(const CORBA::Any &any);
	/**
	 *	Command Trace related method
	 *	Description: 
	 *
	 */
	virtual void trace();
	virtual bool is_Trace_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : Scopix::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(Scopix::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	Scopix::Additional Method prototypes
};

/*----- PROTECTED REGION ID(Scopix::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	Scopix::Additional Classes Definitions

}	//	End of namespace

#endif   //	Scopix_H
