#!/usr/bin/env python
# -*- coding:utf-8 -*- 


##############################################################################
## license :
##============================================================================
##
## File :        PyWebcam.py
## 
## Project :     webcam DS in python
##
## This file is part of Tango device class.
## 
## Tango is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Tango is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Tango.  If not, see <http://www.gnu.org/licenses/>.
## 
##
## $Author :      rp$
##
## $Revision :    $
##
## $Date :        $
##
## $HeadUrl :     $
##============================================================================
##            This file is generated by POGO
##    (Program Obviously used to Generate tango Object)
##
##        (c) - Software Engineering Group - ESRF
##############################################################################

""""""

__all__ = ["PyWebcam", "PyWebcamClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(PyWebcam.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	PyWebcam.additionnal_import

## Device States Description
## ON : 
## OFF : 

class PyWebcam (PyTango.Device_4Impl):

    #--------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(PyWebcam.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PyWebcam.global_variables

    def __init__(self,cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        PyWebcam.init_device(self)
        #----- PROTECTED REGION ID(PyWebcam.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(PyWebcam.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_mydouble_read = 0.0
        self.attr_img_read = [[0.0]]
        #----- PROTECTED REGION ID(PyWebcam.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(PyWebcam.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.always_executed_hook

    #-----------------------------------------------------------------------------
    #    PyWebcam read/write attribute methods
    #-----------------------------------------------------------------------------
    
    def read_mydouble(self, attr):
        self.debug_stream("In read_mydouble()")
        #----- PROTECTED REGION ID(PyWebcam.mydouble_read) ENABLED START -----#
        attr.set_value(self.attr_mydouble_read)
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.mydouble_read
        
    def is_mydouble_allowed(self, attr):
        self.debug_stream("In is_mydouble_allowed()")
        if attr==PyTango.AttReqType.READ_REQ:
            state_ok = not(self.get_state() in [PyTango.DevState.OFF])
        else:
            state_ok = not(self.get_state() in [])
        #----- PROTECTED REGION ID(PyWebcam.is_mydouble_allowed) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.is_mydouble_allowed
        return state_ok
        
    def read_img(self, attr):
        self.debug_stream("In read_img()")
        #----- PROTECTED REGION ID(PyWebcam.img_read) ENABLED START -----#
        attr.set_value(self.attr_img_read)
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.img_read
        
    def is_img_allowed(self, attr):
        self.debug_stream("In is_img_allowed()")
        if attr==PyTango.AttReqType.READ_REQ:
            state_ok = not(self.get_state() in [PyTango.DevState.OFF])
        else:
            state_ok = not(self.get_state() in [])
        #----- PROTECTED REGION ID(PyWebcam.is_img_allowed) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.is_img_allowed
        return state_ok
        
    
    def read_mydynamicattr(self, attr):
        self.debug_stream("In read_mydynamicattr()")
        #----- PROTECTED REGION ID(PyWebcam.mydynamicattr_read) ENABLED START -----#
        attr.set_value(self.attr_mydynamicattr_read)
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.mydynamicattr_read
        
    
    def initialize_dynamic_attributes(self):
        self.debug_stream("In initialize_dynamic_attributes()")
        
        #   Example to add dynamic attributes
        #   Copy inside the folowing protected area to instanciate at startup.
        
        """   For Attribute mydynamicattr
        mymydynamicattr = PyTango.Attr('Mymydynamicattr', PyTango.DevDouble, PyTango.READ)
        self.add_attribute(mymydynamicattr,PyWebcam.read_mydynamicattr, None, None)
        self.attr_mydynamicattr_read = 0.0
        """
        
        #----- PROTECTED REGION ID(PyWebcam.initialize_dynamic_attributes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.initialize_dynamic_attributes
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(PyWebcam.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.read_attr_hardware


    #-----------------------------------------------------------------------------
    #    PyWebcam command methods
    #-----------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(PyWebcam.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PyWebcam.programmer_methods

class PyWebcamClass(PyTango.DeviceClass):
    #--------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(PyWebcam.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PyWebcam.global_class_variables

    def dyn_attr(self, dev_list):
        """Invoked to create dynamic attributes for the given devices.
        Default implementation calls
        :meth:`PyWebcam.initialize_dynamic_attributes` for each device
    
        :param dev_list: list of devices
        :type dev_list: :class:`PyTango.DeviceImpl`"""
    
        for dev in dev_list:
            try:
                dev.initialize_dynamic_attributes()
            except:
                import traceback
                dev.warn_stream("Failed to initialize dynamic attributes")
                dev.debug_stream("Details: " + traceback.format_exc())
        #----- PROTECTED REGION ID(PyWebcam.dyn_attr) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.dyn_attr

    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'mydouble':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'img':
            [[PyTango.DevDouble,
            PyTango.IMAGE,
            PyTango.READ, 640, 480],
            {
                'label': "webcam image",
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(PyWebcamClass,PyWebcam,'PyWebcam')
        #----- PROTECTED REGION ID(PyWebcam.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyWebcam.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed,e:
        print '-------> Received a DevFailed exception:',e
    except Exception,e:
        print '-------> An unforeseen exception occured....',e

if __name__ == '__main__':
    main()
