/*----- PROTECTED REGION ID(WebCam.h) ENABLED START -----*/
//=============================================================================
//
// file :        WebCam.h
//
// description : Include file for the WebCam class
//
// project :     usb webcam device server
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef WebCam_H
#define WebCam_H

#include <tango.h>
#include "opencv2/opencv.hpp"


/*----- PROTECTED REGION END -----*/	//	WebCam.h

/**
 *  WebCam class description:
 *    
 */

namespace WebCam_ns
{
/*----- PROTECTED REGION ID(WebCam::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	WebCam::Additional Class Declarations

class WebCam : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(WebCam::Data Members) ENABLED START -----*/

//	Add your own data members
	cv::VideoCapture *cap;
	cv::Mat frame;
/*----- PROTECTED REGION END -----*/	//	WebCam::Data Members


//	Attribute data members
public:
	Tango::DevDouble	*attr_Img_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	WebCam(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	WebCam(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	WebCam(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~WebCam() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : WebCam::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute Img related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Image max = 640 x 480
 */
	virtual void read_Img(Tango::Attribute &attr);
	virtual bool is_Img_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : WebCam::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command GetFrame related method
	 *	Description: 
	 *
	 */
	virtual void get_frame();
	virtual bool is_GetFrame_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : WebCam::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(WebCam::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	WebCam::Additional Method prototypes
};

/*----- PROTECTED REGION ID(WebCam::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	WebCam::Additional Classes Definitions

}	//	End of namespace

#endif   //	WebCam_H
