/*----- PROTECTED REGION ID(WebCamClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        WebCamClass.h
//
// description : Include for the WebCam root class.
//               This class is the singleton class for
//                the WebCam device class.
//               It contains all properties and methods which the 
//               WebCam requires only once e.g. the commands.
//
// project :     usb webcam device server
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef WebCamClass_H
#define WebCamClass_H

#include <tango.h>
#include <WebCam.h>


/*----- PROTECTED REGION END -----*/	//	WebCamClass.h


namespace WebCam_ns
{
/*----- PROTECTED REGION ID(WebCamClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	WebCamClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute Img class definition
class ImgAttrib: public Tango::ImageAttr
{
public:
	ImgAttrib():ImageAttr("Img",
			Tango::DEV_DOUBLE, Tango::READ, 640, 480) {};
	~ImgAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<WebCam *>(dev))->read_Img(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<WebCam *>(dev))->is_Img_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command GetFrame class definition
class GetFrameClass : public Tango::Command
{
public:
	GetFrameClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	GetFrameClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~GetFrameClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<WebCam *>(dev))->is_GetFrame_allowed(any);}
};


/**
 *	The WebCamClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  WebCamClass : public Tango::DeviceClass
#else
class WebCamClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(WebCamClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	WebCamClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static WebCamClass *init(const char *);
		static WebCamClass *instance();
		~WebCamClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		WebCamClass(string &);
		static WebCamClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	WebCam_H
