/*----- PROTECTED REGION ID(WebCamStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        WebCamStateMachine.cpp
//
// description : State machine file for the WebCam class
//
// project :     usb webcam device server
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <WebCam.h>

/*----- PROTECTED REGION END -----*/	//	WebCam::WebCamStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace WebCam_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : WebCam::is_Img_allowed()
 *	Description : Execution allowed for Img attribute
 */
//--------------------------------------------------------
bool WebCam::is_Img_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Img attribute in read access.
	/*----- PROTECTED REGION ID(WebCam::ImgStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	WebCam::ImgStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : WebCam::is_GetFrame_allowed()
 *	Description : Execution allowed for GetFrame attribute
 */
//--------------------------------------------------------
bool WebCam::is_GetFrame_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetFrame command.
	/*----- PROTECTED REGION ID(WebCam::GetFrameStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	WebCam::GetFrameStateAllowed
	return true;
}

}	//	End of namespace
