/*----- PROTECTED REGION ID(LFG.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        LFG.cpp
//
// description : C++ source for the LFG class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               LFG are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <LFG.h>
#include <LFGClass.h>

/*----- PROTECTED REGION END -----*/	//	LFG.cpp

/**
 *  LFG class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  GetDate       |  get_date
//  Multiply      |  multiply
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//================================================================

namespace LFG_ns
{
/*----- PROTECTED REGION ID(LFG::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	LFG::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : LFG::LFG()
 *	Description : Constructors for a Tango device
 *                implementing the classLFG
 */
//--------------------------------------------------------
LFG::LFG(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(LFG::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	LFG::constructor_1
}
//--------------------------------------------------------
LFG::LFG(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(LFG::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	LFG::constructor_2
}
//--------------------------------------------------------
LFG::LFG(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(LFG::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	LFG::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : LFG::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void LFG::delete_device()
{
	DEBUG_STREAM << "LFG::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(LFG::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	LFG::delete_device
}

//--------------------------------------------------------
/**
 *	Method      : LFG::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void LFG::init_device()
{
	DEBUG_STREAM << "LFG::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(LFG::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	LFG::init_device_before
	
	//	No device property to be read from database
	
	/*----- PROTECTED REGION ID(LFG::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	LFG::init_device
}


//--------------------------------------------------------
/**
 *	Method      : LFG::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void LFG::always_executed_hook()
{
	DEBUG_STREAM << "LFG::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(LFG::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	LFG::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : LFG::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void LFG::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "LFG::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(LFG::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LFG::read_attr_hardware
}


//--------------------------------------------------------
/**
 *	Method      : LFG::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void LFG::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(LFG::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	LFG::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command GetDate related method
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevString LFG::get_date(Tango::DevLong argin)
{
	Tango::DevString argout=new char[100];
	DEBUG_STREAM << "LFG::GetDate()  - " << device_name << " argin " << argin << endl;
	/*----- PROTECTED REGION ID(LFG::get_date) ENABLED START -----*/
	
	//	Add your own code
	string res="hello birine";
	strcpy(argout,res.c_str());
	/*----- PROTECTED REGION END -----*/	//	LFG::get_date
	return argout;
}
//--------------------------------------------------------
/**
 *	Command Multiply related method
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevLong LFG::multiply(const Tango::DevVarStringArray *argin)
{
	Tango::DevLong argout=123;
	DEBUG_STREAM << "LFG::Multiply()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(LFG::multiply) ENABLED START -----*/
	cout << "devvarstringarray " << argin[0][1] <<endl;
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LFG::multiply
	return argout;
}

/*----- PROTECTED REGION ID(LFG::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	LFG::namespace_ending
} //	namespace
