/*----- PROTECTED REGION ID(LFGStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        LFGStateMachine.cpp
//
// description : State machine file for the LFG class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <LFG.h>

/*----- PROTECTED REGION END -----*/	//	LFG::LFGStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace LFG_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LFG::is_GetDate_allowed()
 *	Description : Execution allowed for GetDate attribute
 */
//--------------------------------------------------------
bool LFG::is_GetDate_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetDate command.
	/*----- PROTECTED REGION ID(LFG::GetDateStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LFG::GetDateStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LFG::is_Multiply_allowed()
 *	Description : Execution allowed for Multiply attribute
 */
//--------------------------------------------------------
bool LFG::is_Multiply_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Multiply command.
	/*----- PROTECTED REGION ID(LFG::MultiplyStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LFG::MultiplyStateAllowed
	return true;
}

}	//	End of namespace
